In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
fear_df = pd.read_csv("../data/fear_greed_index.csv")
trade_df = pd.read_csv("../data/historical_data.csv")

### Part A :- Exploring The Data & Data Preparation

#### 1. Load both datasets and analyze

In [3]:
print("Shape of fear_df :",fear_df.shape)
print("Shape of trade_df :",trade_df.shape)

Shape of fear_df : (2644, 4)
Shape of trade_df : (211224, 16)

In [4]:
fear_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2644 entries, 0 to 2643
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   timestamp       2644 non-null   int64
 1   value           2644 non-null   int64
 2   classification  2644 non-null   object
 3   date            2644 non-null   object
dtypes: int64(2), object(2)
memory usage: 82.8+ KB

In [5]:
trade_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211224 entries, 0 to 211223
Data columns (total 16 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Account           211224 non-null  object
 1   Coin              211224 non-null  object
 2   Execution Price   211224 non-null  float64
 3   Size Tokens       211224 non-null  float64
 4   Size USD          211224 non-null  float64
 5   Side              211224 non-null  object
 6   Timestamp IST     211224 non-null  object
 7   Start Position    211224 non-null  float64
 8   Direction         211224 non-null  object
 9   Closed PnL        211224 non-null  float64
 10  Transaction Hash  211224 non-null  object
 11  Order ID          211224 non-null  int64
 12  Crossed           211224 non-null  bool
 13  Fee               211224 non-null  float64
 14  Trade ID          211224 non-null  float64
 15  Timestamp         211224 non-null  float64
dtypes: bool(1), float64(8), int64(1), object(6)
memory usage: 24.4+ MB

In [6]:
fear_df.head()

    timestamp  value classification        date
0  1517463000     30           Fear  2018-02-01
1  1517549400     15   Extreme Fear  2018-02-02
2  1517635800     40           Fear  2018-02-03
3  1517722200     24   Extreme Fear  2018-02-04
4  1517808600     11   Extreme Fear  2018-02-05

In [7]:
trade_df.head()

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,02-12-2024 22:50,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,02-12-2024 22:50,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,1.730000e+12
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,02-12-2024 22:50,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,6.600000e+14,1.730000e+12
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,02-12-2024 22:50,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1.080000e+15,1.730000e+12
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,02-12-2024 22:50,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1.050000e+15,1.730000e+12

In [8]:
fear_df.isnull().sum()

timestamp         0
value             0
classification    0
date              0
dtype: int64

In [9]:
trade_df.isnull().sum()

Account             0
Coin                0
Execution Price     0
Size Tokens         0
Size USD            0
Side                0
Timestamp IST       0
Start Position      0
Direction           0
Closed PnL          0
Transaction Hash    0
Order ID            0
Crossed             0
Fee                 0
Trade ID            0
Timestamp           0
dtype: int64

In [10]:
fear_df.duplicated().sum()

np.int64(0)

In [11]:
trade_df.duplicated().sum()

np.int64(0)

In [12]:
fear_df.describe()

          timestamp        value
count  2.644000e+03  2644.000000
mean   1.631899e+09    46.981089
std    6.597967e+07    21.827680
min    1.517463e+09     5.000000
25%    1.574811e+09    28.000000
50%    1.631900e+09    46.000000
75%    1.688989e+09    66.000000
max    1.746164e+09    95.000000

In [13]:
trade_df.describe()

,Execution Price,Size Tokens,Size USD,Start Position,Closed PnL,Order ID,Fee,Trade ID,Timestamp
count,211224.000000,2.112240e+05,2.112240e+05,2.112240e+05,211224.000000,2.112240e+05,211224.000000,2.112240e+05,2.112240e+05
mean,11414.723350,4.623365e+03,5.639451e+03,-2.994625e+04,48.749001,6.965388e+10,1.163967,5.628549e+14,1.737744e+12
std,29447.654868,1.042729e+05,3.657514e+04,6.738074e+05,919.164828,1.835753e+10,6.758854,3.257565e+14,8.689920e+09
min,0.000005,8.740000e-07,0.000000e+00,-1.433463e+07,-117990.104100,1.732711e+08,-1.175712,0.000000e+00,1.680000e+12
25%,4.854700,2.940000e+00,1.937900e+02,-3.762311e+02,0.000000,5.983853e+10,0.016121,2.810000e+14,1.740000e+12
50%,18.280000,3.200000e+01,5.970450e+02,8.472793e+01,0.000000,7.442939e+10,0.089578,5.620000e+14,1.740000e+12
75%,101.580000,1.879025e+02,2.058960e+03,9.337278e+03,5.792797,8.335543e+10,0.393811,8.460000e+14,1.740000e+12
max,109004.000000,1.582244e+07,3.921431e+06,3.050948e+07,135329.090100,9.014923e+10,837.471593,1.130000e+15,1.750000e+12

#### 2. Conversion of dates and alignment of both datasets

In [14]:
fear_df["date"] = pd.to_datetime(fear_df["date"]).dt.normalize()
fear_df["date"].head()

0   2018-02-01
1   2018-02-02
2   2018-02-03
3   2018-02-04
4   2018-02-05
Name: date, dtype: datetime64[ns]

In [15]:
trade_df["Timestamp IST"] = pd.to_datetime(trade_df["Timestamp IST"], dayfirst=True)
trade_df["date"] = trade_df["Timestamp IST"].dt.normalize()
trade_df.head()

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp,date
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,2024-12-02 22:50:00,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12,2024-12-02
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,2024-12-02 22:50:00,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,1.730000e+12,2024-12-02
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,2024-12-02 22:50:00,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,6.600000e+14,1.730000e+12,2024-12-02
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,2024-12-02 22:50:00,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1.080000e+15,1.730000e+12,2024-12-02
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,2024-12-02 22:50:00,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1.050000e+15,1.730000e+12,2024-12-02

In [16]:
merged_df = pd.merge(trade_df, fear_df[["value", "classification", "date"]] , on="date", how="left")
merged_df = merged_df.rename(columns={"value" : "Value", "classification" : "Classification", "date" : "Date"})
merged_df.head()

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp,Date,Value,Classification
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,2024-12-02 22:50:00,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12,2024-12-02,80.0,Extreme Greed
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,2024-12-02 22:50:00,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,1.730000e+12,2024-12-02,80.0,Extreme Greed
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,2024-12-02 22:50:00,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,6.600000e+14,1.730000e+12,2024-12-02,80.0,Extreme Greed
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,2024-12-02 22:50:00,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1.080000e+15,1.730000e+12,2024-12-02,80.0,Extreme Greed
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,2024-12-02 22:50:00,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1.050000e+15,1.730000e+12,2024-12-02,80.0,Extreme Greed

In [17]:
merged_df = merged_df.dropna(subset=["Classification"])

In [18]:
merged_df['Classification'].value_counts()

Classification
Fear             61837
Greed            50303
Extreme Greed    39992
Neutral          37686
Extreme Fear     21400
Name: count, dtype: int64

In [19]:
# merged_df.to_csv("../data/merged.csv", index=False)

#### 3. Key Metrics

##### (i) Daily PnL Per Trader/User

In [20]:
trader_PnL_df = merged_df.groupby(["Account", "Date"])["Closed PnL"].sum().reset_index()
trader_PnL_df = trader_PnL_df.rename(columns={"Closed PnL" : "Daily PnL"})
trader_PnL_df.head()

                                      Account       Date  Daily PnL
0  0x083384f897ee0f19899168e3b1bec365f52a9012 2024-11-11        0.0
1  0x083384f897ee0f19899168e3b1bec365f52a9012 2024-11-17        0.0
2  0x083384f897ee0f19899168e3b1bec365f52a9012 2024-11-18        0.0
3  0x083384f897ee0f19899168e3b1bec365f52a9012 2024-11-22   -21227.0
4  0x083384f897ee0f19899168e3b1bec365f52a9012 2024-11-26     1603.1

##### (ii) Win Rate, Average Trade Size

In [21]:
merged_df["Win"] = merged_df["Closed PnL"] > 0

In [22]:
win_rate_df = merged_df.groupby("Account").agg(Winning_Trade=("Win", "sum"), Total_Trade=("Win", "count")).reset_index()
win_rate_df["Win Rate (%)"] = (win_rate_df["Winning_Trade"] / win_rate_df["Total_Trade"]) * 100
win_rate_df.head()

,Account,Winning_Trade,Total_Trade,Win Rate (%)
0,0x083384f897ee0f19899168e3b1bec365f52a9012,1373,3818,35.961236
1,0x23e7a7f8d14b550961925fbfdaa92f5d195ba5bd,3223,7280,44.271978
2,0x271b280974205ca63b716753467d5a371de622ab,1150,3809,30.191651
3,0x28736f43f1e871e6aa8b1148d38d4994275d72c4,5838,13311,43.858463
4,0x2c229d22b100a7beb69122eed721cee9b24011dd,1684,3239,51.991355

In [23]:
avg_trade_df = merged_df.groupby("Account")["Size USD"].mean().reset_index()
avg_trade_df = avg_trade_df.rename(columns={"Size USD" : "Avg Trade Size (USD)"})
avg_trade_df.head()

                                      Account  Avg Trade Size (USD)
0  0x083384f897ee0f19899168e3b1bec365f52a9012          16159.576734
1  0x23e7a7f8d14b550961925fbfdaa92f5d195ba5bd           1653.226327
2  0x271b280974205ca63b716753467d5a371de622ab           8893.000898
3  0x28736f43f1e871e6aa8b1148d38d4994275d72c4            507.626933
4  0x2c229d22b100a7beb69122eed721cee9b24011dd           3138.894782

##### (iii) Leverage Distribution

##### Note
The provided historical trader dataset does not contain a leverage field. Therefore, leverage distribution could not be analyzed directly. The remaining requested metrics were computed using the available data.

##### (iv) Number Of Trades Per Day

In [24]:
trades_per_day_df = merged_df.groupby("Date")["Trade ID"].count().reset_index()
trades_per_day_df = trades_per_day_df.rename(columns={"Trade ID" : "Number of Trades"})
trades_per_day_df.head()

        Date  Number of Trades
0 2023-05-01                 3
1 2023-12-05                 9
2 2023-12-14                11
3 2023-12-15                 2
4 2023-12-16                 3

##### (v) Long/Short Ratio

In [25]:
long_trades = (merged_df["Direction"].isin(("Open Long", "Close Long"))).sum()
short_trades = (merged_df["Direction"].isin(("Open Short", "Close Short"))).sum()
print("Number of long trades :",long_trades)
print("Number of short trades :",short_trades)

long_short_ratio = long_trades/short_trades
print("Long/Short ratio :",long_short_ratio)

Number of long trades : 98573
Number of short trades : 75748
Long/Short ratio : 1.3013280878703068

In [26]:
long_short_df = pd.DataFrame({
    "Long Trades": [long_trades],
    "Short Trades": [short_trades],
    "Long/Short Ratio": [long_short_ratio]
})
long_short_df

   Long Trades  Short Trades  Long/Short Ratio
0        98573         75748          1.301328

### Part B :- Analysis

#### Q1 :- Does performance (PnL, win rate, drawdown proxy) differ between Fear vs Greed days?

In [28]:
win_rate_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Account        32 non-null     object
 1   Winning_Trade  32 non-null     int64
 2   Total_Trade    32 non-null     int64
 3   Win Rate (%)   32 non-null     float64
dtypes: float64(1), int64(2), object(1)
memory usage: 1.1+ KB

In [29]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 211218 entries, 0 to 211223
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Account           211218 non-null  object
 1   Coin              211218 non-null  object
 2   Execution Price   211218 non-null  float64
 3   Size Tokens       211218 non-null  float64
 4   Size USD          211218 non-null  float64
 5   Side              211218 non-null  object
 6   Timestamp IST     211218 non-null  datetime64[ns]
 7   Start Position    211218 non-null  float64
 8   Direction         211218 non-null  object
 9   Closed PnL        211218 non-null  float64
 10  Transaction Hash  211218 non-null  object
 11  Order ID          211218 non-null  int64
 12  Crossed           211218 non-null  bool
 13  Fee               211218 non-null  float64
 14  Trade ID          211218 non-null  float64
 15  Timestamp         211218 non-null  float64
 16  Date              211218 non-null  datetime64[ns]
 17  Value             211218 non-null  float64
 18  Classification    211218 non-null  object
 19  Win               211218 non-null  bool
dtypes: bool(2), datetime64[ns](2), float64(9), int64(1), object(6)
memory usage: 31.0+ MB

In [30]:
merged_df.head()

,Account,Coin,Execution Price,Size Tokens,Size USD,Side,Timestamp IST,Start Position,Direction,Closed PnL,Transaction Hash,Order ID,Crossed,Fee,Trade ID,Timestamp,Date,Value,Classification,Win
0,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9769,986.87,7872.16,BUY,2024-12-02 22:50:00,0.000000,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.345404,8.950000e+14,1.730000e+12,2024-12-02,80.0,Extreme Greed,False
1,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9800,16.00,127.68,BUY,2024-12-02 22:50:00,986.524596,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.005600,4.430000e+14,1.730000e+12,2024-12-02,80.0,Extreme Greed,False
2,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9855,144.09,1150.63,BUY,2024-12-02 22:50:00,1002.518996,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050431,6.600000e+14,1.730000e+12,2024-12-02,80.0,Extreme Greed,False
3,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9874,142.98,1142.04,BUY,2024-12-02 22:50:00,1146.558564,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.050043,1.080000e+15,1.730000e+12,2024-12-02,80.0,Extreme Greed,False
4,0xae5eacaf9c6b9111fd53034a602c192a04e082ed,@107,7.9894,8.73,69.75,BUY,2024-12-02 22:50:00,1289.488521,Buy,0.0,0xec09451986a1874e3a980418412fcd0201f500c95bac...,52017706630,True,0.003055,1.050000e+15,1.730000e+12,2024-12-02,80.0,Extreme Greed,False